import os

class Config:
    GOOGLE_MAPS_API_KEY = os.getenv('GOOGLE_MAPS_API_KEY', 'default_key_if_not_set')

    GRAPH_SENSOR_LOCATIONS_FILE_PATH = os.getenv('GRAPH_SENSOR_LOCATIONS_FILE_PATH')

    REAL_SPEED_FILE_PATH = os.getenv('REAL_SPEED_FILE_PATH')
    PREDICTED_SPEED_FILE_PATH = os.getenv('PREDICTED_SPEED_FILE_PATH')

    COLLISION_FILE_PATH = os.getenv('COLLISION_FILE_PATH')
    COLLISION_REAL_SPEED_FILE_PATH = os.getenv('COLLISION_REAL_SPEED_FILE_PATH')
    COLLISION_PREDICTED_SPEED_FILE_PATH = os.getenv('COLLISION_PREDICTED_SPEED_FILE_PATH')