export const styles = {
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '1rem',
  },
  card: {
    border: '1px solid #e5e7eb',
    borderRadius: '0.5rem',
    padding: '1rem',
  },
  fullWidth: {
    gridColumn: '1 / -1',
  },
  cardTitle: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontSize: '1.25rem',
    fontWeight: 'bold',
    padding: '0.3rem 0 1rem 0',
  },
  mapContainer: {
    width: '100%',
    height: '30rem',
    borderRadius: '0.5rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  mapContainerStyle: {
    width: '100%',
    height: '100%',
  },
  modalContent: {
    top: '50%',
    left: '50%',
    right: 'auto',
    bottom: 'auto',
    marginRight: '-50%',
    transform: 'translate(-50%, -50%)',
    width: '90%',
    height: '100%',
  },
  modalCloseButton: {
    position: 'absolute',
    top: '0.6rem',
    right: '0.6rem',
    backgroundColor: 'transparent',
    color: '#000',
    border: 'none',
    fontSize: '2rem',
    cursor: 'pointer',
    fontWeight: 'bold',
    padding: '0.3rem',
    transition: 'color 0.2s ease',
  },
};
