export const styles = {
  container: {
    maxWidth: '90%',
    margin: '0 auto',
    padding: '1rem',
  },
  tabContainer: {
    display: 'flex',
    gap: '1rem',
    borderBottom: '1px solid #e5e7eb',
    marginBottom: '1rem',
  },
  tabButton: {
    padding: '0.5rem 1rem',
    border: 'none',
    background: 'none',
    cursor: 'pointer',
  },
  activeTab: {
    borderBottom: '2px solid #3b82f6',
    fontWeight: 'bold',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '1rem',
  },
  card: {
    border: '1px solid #e5e7eb',
    borderRadius: '0.5rem',
    padding: '1rem',
  },
  fullWidth: {
    gridColumn: '1 / -1',
  },
  fixheight: {
    height: '400px',
  },
  cardTitle: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontSize: '1.25rem',
    fontWeight: 'bold',
    padding: '0.3rem 0 1rem 0',
  },
  mapContainer: {
    width: '100%',
    height: '40rem',
    borderRadius: '0.5rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  mapText: {
    textAlign: 'center',
    color: '#6b7280',
    width: '100%',
    height: '100%',
  },
  mapContainerStyle: {
    width: '100%',
    height: '100%',
  },
  chartContainer: {
    height: '500px',
  },
  dateLabel: {
    display: 'flex',
    flexDirection: 'column',
    fontSize: '1rem',
    marginBottom: '0.5rem',
  },
  dateInput: {
    marginTop: '0.5rem',
    padding: '0.5rem',
    border: '1px solid #e5e7eb',
    borderRadius: '4px',
    fontSize: '1rem',
  },
  selectedDateText: {
    fontSize: '1rem',
    color: '#6b7280',
  },
  analyzeButton: {
    marginTop: '10px',
    padding: '0.5rem 12px',
    backgroundColor: '#007bff',
    color: 'white',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
  },
  modalContent: {
    top: '50%',
    left: '50%',
    right: 'auto',
    bottom: 'auto',
    marginRight: '-50%',
    transform: 'translate(-50%, -50%)',
    width: '90%',
    height: '90%',
  },
  modalCloseButton: {
    position: 'absolute',
    top: '0.6rem',
    right: '0.6rem',
    backgroundColor: 'transparent',
    color: '#000',
    border: 'none',
    fontSize: '2rem',
    cursor: 'pointer',
    fontWeight: 'bold',
    padding: '5px',
    transition: 'color 0.2s ease',
  },
};
